import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createWorker} from './worker.mjs';
import {normalizeRoomItems} from './room-items.mjs';
const env={APP_ACCESS_PASSWORD:'test-only-password-2026',SESSION_SECRET:'test-only-session-secret-not-real-'.repeat(2)};
const configured={...env,FEISHU_APP_ID:'TEST_APP',FEISHU_APP_SECRET:'PRIVATE_TEST_APP_SECRET',FEISHU_APP_TOKEN:'TEST_BASE',FEISHU_TABLE_ID:'TEST_TABLE'};
const base='https://echofind.example';
function request(path,options={}){return new Request(base+path,options);}
async function login(worker,bindings=env,ip='192.0.2.1'){
 const r=await worker.fetch(request('/api/login',{method:'POST',headers:{'content-type':'application/json',origin:base,'CF-Connecting-IP':ip},body:JSON.stringify({password:bindings.APP_ACCESS_PASSWORD})}),bindings);
 assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];
}
const record=(strength=60,station)=>({record_id:'r1',fields:{'编号':'tag1','强度':strength,'时间':'test','基站':station,'secret':'PRIVATE_RECORD'}});
function fixture(){let clock=Date.now(),calls=0,rows=[record()],mode='normal';const fetcher=async(url,options)=>{
 calls++;if(mode==='network')throw Error('PRIVATE_NETWORK_ERROR');
 if(String(url).includes('/auth/')){assert.equal(JSON.parse(options.body).app_secret,configured.FEISHU_APP_SECRET);return Response.json({code:0,tenant_access_token:'PRIVATE_TENANT_TOKEN',expire:7200});}
 assert.equal(options.headers.Authorization,'Bearer PRIVATE_TENANT_TOKEN');
 if(mode==='business')return Response.json({code:999,msg:'PRIVATE_PROVIDER_ERROR'});
 if(mode==='broken')return Response.json({code:0,data:{items:rows,has_more:true}});
 if(mode==='pagination'){const page=new URL(url).searchParams.get('page_token');return Response.json({code:0,data:{items:page?[{record_id:'r2',fields:{'编号':'tag2','强度':20}}]:rows,has_more:!page,page_token:page?'':'next'}});}
 return Response.json({code:0,data:{items:rows,has_more:false}});
 };return {worker:createWorker({fetcher,now:()=>clock}),fetcher,advance:ms=>clock+=ms,get calls(){return calls},set rows(v){rows=v},set mode(v){mode=v}};}
const items=(worker,cookie,seed='a'.repeat(32),bindings=configured)=>worker.fetch(request('/api/room-items?placementSeed='+seed,{headers:{cookie}}),bindings);

test('the overview, backend source, private files and unused APIs return 404',async()=>{const w=createWorker();for(const p of ['/','/index.html','/dashboard.js','/.env','/feishu_test.py','/worker.mjs','/room-items.mjs','/wrangler.jsonc','/package.json','/api/dashboard','/api/ai/chat','/api/document-view','/blender/room.blend','/%2findex.html'])assert.equal((await w.fetch(request(p),env)).status,404,p);});
test('unconfigured deployment fails closed and explains setup only at login',async()=>{const w=createWorker();assert.deepEqual(await (await w.fetch(request('/api/session'),{})).json(),{authenticated:false,passwordRequired:true});const r=await w.fetch(request('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),{});assert.equal(r.status,503);assert.equal((await items(w,'','a'.repeat(32),{})).status,401);});
test('login rejects wrong password and cross-site requests',async()=>{const w=createWorker();const post=(password,origin=base)=>w.fetch(request('/api/login',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify({password})}),env);assert.equal((await post('wrong')).status,401);assert.equal((await post(env.APP_ACCESS_PASSWORD,'https://evil.example')).status,403);});
test('login cookie is signed, secure, HttpOnly and never contains credentials',async()=>{const w=createWorker();const r=await w.fetch(request('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:env.APP_ACCESS_PASSWORD})}),env);assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');for(const x of ['HttpOnly','Secure','SameSite=Strict','Path=/'])assert.ok(cookie.includes(x));assert.ok(!cookie.includes(env.APP_ACCESS_PASSWORD));assert.ok(!cookie.includes(env.SESSION_SECRET));assert.equal((await (await w.fetch(request('/api/session',{headers:{cookie:cookie.split(';')[0]}}),env)).json()).authenticated,true);});
test('sessions survive different Worker instances without an in-memory session map',async()=>{const cookie=await login(createWorker());assert.equal((await (await createWorker().fetch(request('/api/session',{headers:{cookie}}),env)).json()).authenticated,true);});
test('tampering, expiry, password rotation and secret rotation invalidate sessions',async()=>{let clock=Date.now();const w=createWorker({now:()=>clock}),cookie=await login(w);const check=async(c,e=env)=>(await (await w.fetch(request('/api/session',{headers:{cookie:c}}),e)).json()).authenticated;assert.equal(await check(cookie.slice(0,-1)+(cookie.endsWith('a')?'b':'a')),false);assert.equal(await check(cookie,{...env,APP_ACCESS_PASSWORD:'changed-password-2026'}),false);assert.equal(await check(cookie,{...env,SESSION_SECRET:'changed-secret-longer-than-thirty-two-characters'}),false);clock+=8*3600000+1000;assert.equal(await check(cookie),false);});
test('logout clears the current browser cookie',async()=>{const r=await createWorker().fetch(request('/api/session',{method:'DELETE',headers:{origin:base}}),env);assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
test('login throttling is enabled and platform rate-limit binding is honored',async()=>{const w=createWorker();for(let i=0;i<8;i++)assert.equal((await w.fetch(request('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:'{"password":"wrong"}'}),env)).status,401);assert.equal((await w.fetch(request('/api/login',{method:'POST'}),env)).status,429);assert.equal((await createWorker().fetch(request('/api/login',{method:'POST'}),{...env,LOGIN_RATE_LIMITER:{limit:async()=>({success:false})}})).status,429);});
test('oversized, non-JSON and malformed login bodies are rejected',async()=>{const w=createWorker();for(const [body,type,status]of [['x'.repeat(9000),'application/json',413],['x','text/plain',415],['{','application/json',400],['null','application/json',400]])assert.equal((await w.fetch(request('/api/login',{method:'POST',headers:{'content-type':type},body}),env)).status,status);});
test('items are protected, seeds are validated before upstream access',async()=>{const f=fixture();assert.equal((await items(f.worker,'')).status,401);const c=await login(f.worker);assert.equal((await items(f.worker,c,'bad')).status,400);assert.equal(f.calls,0);});
test('missing Feishu configuration is explicit and never invents items',async()=>{const w=createWorker(),c=await login(w);const r=await items(w,c,'a'.repeat(32),env);assert.equal(r.status,200);const data=await r.json();assert.equal(data.source,'unconfigured');assert.deepEqual(data.items,[]);});
test('Feishu fields are mapped but credentials and arbitrary record fields stay private',async()=>{const f=fixture(),c=await login(f.worker),r=await items(f.worker,c);assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');const text=await r.text();assert.ok(!text.includes('PRIVATE'));const data=JSON.parse(text);assert.equal(data.items.length,1);assert.equal(data.items[0].station,'LeftUpper');assert.equal(data.items[0].number,'tag1');assert.equal(data.pollIntervalMs,5000);assert.equal(f.calls,2);});
test('automatic polling stays put and manual reload changes placement',async()=>{const f=fixture(),c=await login(f.worker);const a=await (await items(f.worker,c)).json();f.advance(2000);const b=await (await items(f.worker,c)).json();const d=await (await items(f.worker,c,'b'.repeat(32))).json();assert.deepEqual(a.items[0].position,b.items[0].position);assert.notDeepEqual(a.items[0].position,d.items[0].position);assert.equal(a.items[0].distance,d.items[0].distance);});
test('position remains stable across cold starts',async()=>{const f=fixture(),c=await login(f.worker);const a=await (await items(f.worker,c)).json();const b=await (await items(createWorker({fetcher:f.fetcher}),c)).json();assert.deepEqual(a.items,b.items);});
test('cached and concurrent requests share upstream work',async()=>{const f=fixture(),c=await login(f.worker);await Promise.all(Array.from({length:8},()=>items(f.worker,c)));assert.equal(f.calls,2);await items(f.worker,c);assert.equal(f.calls,2);});
test('signal edits, additions, removals and cleared strengths are picked up',async()=>{const f=fixture(),c=await login(f.worker);const before=await (await items(f.worker,c)).json();f.rows=[record(90),{record_id:'new',fields:{'编号':'new','强度':10}}];f.advance(2000);const changed=await (await items(f.worker,c)).json();assert.equal(changed.items.length,2);assert.ok(changed.items[0].distance<before.items[0].distance);f.rows=[record('')];f.advance(2000);assert.deepEqual((await (await items(f.worker,c)).json()).items,[]);});
test('pagination is read fully and incomplete responses are errors',async()=>{const f=fixture(),c=await login(f.worker);f.mode='pagination';assert.equal((await (await items(f.worker,c)).json()).items.length,2);f.advance(2000);f.mode='broken';assert.equal((await items(f.worker,c)).status,502);});
test('upstream failures are sanitized and recovery is not cached as failure',async()=>{const f=fixture(),c=await login(f.worker);for(const mode of ['network','business']){f.mode=mode;const r=await items(f.worker,c);assert.equal(r.status,502);assert.ok(!(await r.text()).includes('PRIVATE'));}f.mode='normal';assert.equal((await items(f.worker,c)).status,200);});
test('stronger signal is closer, default receiver stays upper-left, both receivers cover room',()=>{for(const station of ['LeftUpper','RightLower']){const quadrants=new Set();for(let signal=0;signal<=100;signal++)for(let n=0;n<20;n++){const [a]=normalizeRoomItems([record(signal,station)],n.toString(16).padStart(32,'0'));const {x,z}=a.position;assert.ok(Math.abs(x)<=5.651&&Math.abs(z)<=5.651);assert.ok(!(Math.abs(x)<.399&&z<3.949));quadrants.add((x<0?'L':'R')+(z<0?'T':'B'));}assert.equal(quadrants.size,4);}const a=normalizeRoomItems([record(90)],'a'.repeat(32))[0],b=normalizeRoomItems([record(10)],'a'.repeat(32))[0];assert.ok(a.distance<b.distance);assert.equal(a.station,'LeftUpper');assert.equal(normalizeRoomItems([record()],'', 'RightLower')[0].station,'RightLower');});
test('public output has the GLB, complete module graph, no overview or server source',async()=>{const names=await readdir('dist');assert.ok(!names.includes('index.html'));const html=await readFile('dist/control.html','utf8');assert.ok(!html.includes('href="/"'));assert.ok(!html.includes('空间总览'));assert.ok(!html.includes('返回总览'));const glb=await readFile('dist/assets/models/room.glb');assert.equal(glb.toString('ascii',0,4),'glTF');for(const m of ['three.module.js','three.core.js'])assert.ok((await readFile('dist/vendor/three/build/'+m)).length>100);});
test('control route, model response, HEAD and CSP match the deployed files',async()=>{const w=createWorker(),bindings={...env,ASSETS:{fetch:async req=>{let bytes;try{bytes=await readFile('dist'+new URL(req.url).pathname);}catch{return new Response('missing',{status:404});}return new Response(req.method==='HEAD'?null:bytes);}}};const r=await w.fetch(request('/control.html'),bindings);assert.equal(r.status,200);const html=await r.text();const map=html.match(/<script type="importmap">([\s\S]*?)<\/script>/)[1];const digest=createHash('sha256').update(map).digest('base64');assert.ok(r.headers.get('content-security-policy').includes(digest));assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal((await w.fetch(request('/control'),bindings)).status,308);assert.equal((await w.fetch(request('/control.html',{method:'POST'}),bindings)).status,405);assert.equal((await w.fetch(request('/control.html',{method:'HEAD'}),bindings)).status,200);});
test('public demo session bypasses the password overlay without any security secrets',async()=>{const w=createWorker();const r=await w.fetch(request('/api/session'),{PUBLIC_DEMO:'true'});assert.equal(r.status,200);assert.deepEqual(await r.json(),{authenticated:true,passwordRequired:false});assert.equal(r.headers.get('set-cookie'),null);});
test('public demo can read items anonymously without exposing Feishu secrets',async()=>{const f=fixture(),bindings={...configured,PUBLIC_DEMO:'true'};delete bindings.APP_ACCESS_PASSWORD;delete bindings.SESSION_SECRET;const r=await items(f.worker,'','a'.repeat(32),bindings);assert.equal(r.status,200);const text=await r.text();assert.ok(!text.includes('PRIVATE'));assert.equal(JSON.parse(text).items[0].number,'tag1');assert.equal(r.headers.get('set-cookie'),null);});
test('public demo without Feishu still returns a usable empty room state',async()=>{const r=await items(createWorker(),'','a'.repeat(32),{PUBLIC_DEMO:'true'});assert.equal(r.status,200);const data=await r.json();assert.equal(data.source,'unconfigured');assert.deepEqual(data.items,[]);});
test('public demo does not expose overview, unused APIs or source and disables login',async()=>{const w=createWorker(),bindings={PUBLIC_DEMO:'true'};for(const path of ['/','/index.html','/worker.mjs','/.env','/api/dashboard','/api/ai/chat'])assert.equal((await w.fetch(request(path),bindings)).status,404);assert.equal((await w.fetch(request('/api/login',{method:'POST'}),bindings)).status,404);assert.equal((await items(w,'','bad',bindings)).status,400);});
test('public item polling is rate limited per IP, not by a fabricated shared session',async()=>{const w=createWorker(),bindings={PUBLIC_DEMO:'true'};for(let i=0;i<100;i++)assert.equal((await items(w,'','a'.repeat(32),bindings)).status,200);assert.equal((await items(w,'','a'.repeat(32),bindings)).status,429);const r=await w.fetch(request('/api/room-items?placementSeed='+'a'.repeat(32),{headers:{'CF-Connecting-IP':'192.0.2.22'}}),bindings);assert.equal(r.status,200);});
test('public demo deployment is enabled explicitly and the browser respects passwordRequired flow',async()=>{const config=JSON.parse(await readFile('wrangler.jsonc','utf8'));assert.equal(config.vars.PUBLIC_DEMO,'true');const common=await readFile('common.js','utf8');assert.match(common,/if\(session.authenticated\)return/);const readme=await readFile('README.md','utf8');assert.ok(!readme.includes('| APP_ACCESS_PASSWORD |'));assert.ok(!readme.includes('| SESSION_SECRET |'));});